prompt DELETE TEST DATA
SET feedback OFF
SET define OFF

--STG接口表
TRUNCATE TABLE CMAP_SYNC.ETL_STG_LOADLOG;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_BOND_OUT;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_BOND_POSITIONOWN;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_BOND_STRUCTURED;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_CREDITAPPLY;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_CREDITINFO;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_CREDITRATING;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_GROUPGRAPH;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_GROUPWARNING;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_HIGHRISKLIST;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_LIMIT;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_OPERATIONCLEAR;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_OVERDUEINTEREST;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_PBCCREDIT;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_PBCGUAR;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_RULEFACTOR;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_WARNING;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_WARNINGTYPE;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_COMPY_WARNLEVELCHG;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_CUSTOMER;
TRUNCATE TABLE CMAP_SYNC.STG_CMB_CONSTANT;
TRUNCATE TABLE CMAP_SYNC.T_NEWS_COMPANY_FCDB;
TRUNCATE TABLE CMAP_SYNC.T_NEWS_TEXT_FCDB;
TRUNCATE TABLE CMAP_SYNC.TQ_COMP_INFO;
TRUNCATE TABLE CMAP_SYNC.STG_TQ_BD_BASICINFO;
TRUNCATE TABLE CMAP_SYNC.STG_TQ_BD_HIDECREDITCHG;
TRUNCATE TABLE CMAP_SYNC.STG_TQ_BD_NEWHIDECREDIT;


--TGT的行内数据表清理
TRUNCATE TABLE CMAP_APP.ETL_TGT_LOADLOG;
TRUNCATE TABLE CMAP_APP.BOND_POSITION_OUT;
TRUNCATE TABLE CMAP_APP.BOND_POSITION_OWN;
TRUNCATE TABLE CMAP_APP.BOND_POSITION_STRUCTURED;
TRUNCATE TABLE CMAP_APP.COMPY_CREDITAPPLY_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_CREDITINFO_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_CREDITRATING_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_GROUPGRAPH_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_GROUPWARNING_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_HIGHRISKLIST_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_LIMIT_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_OPERATIONCLEAR_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_OVERDUEINTEREST_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_PBCCREDIT_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_PBCGUAR_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_RULEFACTOR_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_WARNING_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_WARNINGTYPE_CMB;
TRUNCATE TABLE CMAP_APP.COMPY_WARNLEVELCHG_CMB;
TRUNCATE TABLE CMAP_APP.CUSTOMER_CMB;
DELETE FROM CMAP_APP.LKP_CONSTANT WHERE CONSTANT_TYPE <= 100;
COMMIT;


--预警
TRUNCATE TABLE CMAP_APP.TMP_COMPY_WARNINGS;
TRUNCATE TABLE CMAP_APP.COMPY_WARNINGS;
TRUNCATE TABLE CMAP_APP.COMPY_WARNINGS_CONTENT;

BEGIN
  CMAP_APP.sp_warnings_finanaudit();
  CMAP_APP.sp_warnings_creditrating();
  CMAP_APP.sp_warnings_bondmarket();
  CMAP_APP.sp_compy_warnings();
END;
/

set feedback on
set define on
prompt Done.
