------基本财务指标+特色财务指标
--吸收投资收到的现金	应付账款	应收账款	预提费用	预收款项	应付票据	应收票据	应付债券	购买商品、接受劳务支付的现金	资本公积金	在建工程	递延收益	一年内的递延收益	递延所得税资产	开发支出	分配股利、利润或偿付利息支付的现金	
--减:财务费用	固定资产  以公允价值计量且其变动计入当期损益的金融资产	加:公允价值变动收益	商誉	所得税	无形资产	应付利息	存货	加:投资收益	长期借款	长期待摊费用	减:管理费用	货币资金	投资活动产生的现金流量净额	经营活动产生的现金流量净额		
--净利润	一年内到期的非流动负债  加:营业外收入	减:营业成本	营业利润	营业收入	其他权益工具	其他流动资产	其他流动负债	其他应付款	其他应收款	归属于母公司股东的净利润	应付职工薪酬	减:销售费用	销售商品、提供劳务收到的现金	
--股本	短期借款	资产总计	负债合计	非流动资产合计	非流动负债合计	归属于母公司股东权益合计	利润总额	股东权益合计	应交税费	交易性金融资产
select zs.EXPOSURE ,zs.company_id,cb.company_nm, to_char(a.rpt_dt,'yyyymmdd') ,  			
accept_inv_rec	,
account_pay	,
account_pay_last_y	,
account_rec	,
account_rec_last_y	,
accrue_expense	,
accrue_expense_last_y	,
advance_receive	,
advance_receive_last_y	,
bill_pay	,
bill_pay_last_y	,
bill_rec	,
bill_rec_last_y	,
bond_pay	,
bond_pay_last_y	,
buygoods_service_pay	,
capital_reserve	,
capital_reserve_last_y	,
construction_progress	,construction_progress_last_y	,construct_pro_bf_last_y	,
defer_income	,
defer_income_oneyear	,
defer_income_oneyear_last_y	,
defer_incometax_asset	,
develop_exp	,
divi_profitorint_pay	,divi_profitorint_pay_last_y	,divi_profitorint_pay_bf_last_y	,
EBIT	,EBIT_last_y	,EBIT_bf_last_y	,
EBITDA	,EBITDA_last_y	,EBITDA_bf_last_y	,
finance_exp	,
fixed_asset	,
fixed_asset_last_y	,
fvalue_fasset	,
fvalue_income	,
good_will	,
income_tax	,
intangible_asset	,
interest_pay	,
inventory	,
inventory_last_y	,
invest_income	,
lt_account_pay	,
lt_account_pay_last_y	,
lt_borrow	,
lt_borrow_last_y	,
ltdefer_asset	,
manage_exp	,
monetary_fund	,
net_inv_cashflow	,
net_operate_cashflow	,net_operate_cashflow_last_y	,net_operate_cashflow_bf_last_y	,
net_profit	,net_profit_last_y	,net_profit_bf_last_y	,
nonl_liab_oneyear	,
nonl_liab_oneyear_last_y	,
nonoperate_reve	,
operate_exp	,
operate_profit	,operate_profit_last_y	,operate_profit_bf_last_y	,
operate_reve	,operate_reve_last_y	,operate_reve_bf_last_y	,
other_equity	,
other_lasset	,
other_lliab	,
other_lliab_last_y	,
other_pay	,
other_pay_last_y	,
other_rec	,
parent_net_profit	,parent_net_profit_last_y	,parent_net_profit_bf_last_y	,
salary_pay	,
salary_pay_last_y	,
sale_exp	,
salegoods_service_rec	,
share_capital	,
share_capital_last_y	,
st_borrow	,
st_borrow_last_y	,
sum_asset	,sum_asset_last_y	,sum_asset_bf_last_y	,
sum_lasset	,
sum_lasset_last_y	,
sum_liab	,
sum_lliab	,
sum_lliab_last_y	,
sum_nonl_asset	,
sum_nonl_asset_last_y	,
sum_nonl_liab	,
sum_parent_equity	,
sum_profit	,sum_profit_last_y	,sum_profit_bf_last_y	,
sum_sh_equity	,sum_sh_equity_last_y	,sum_sh_equity_bf_last_y	,
tax_pay	,
tax_pay_last_y	,
tradef_asset	
 from compy_finance a 
 join compy_finance_last_y  b on a.company_id = b.company_id and a.rpt_dt = b.rpt_dt  and a.rpt_timetype_cd=b.rpt_timetype_cd  			
 join compy_finance_bf_last_y c on a.company_id = c.company_id and a.rpt_dt = c.rpt_dt  and a.rpt_timetype_cd=c.rpt_timetype_cd			
 join(select b.exposure,a.* from compy_exposure a join exposure b on a.exposure_sid = b.exposure_sid where a.client_id=5 and a.is_new=1 and a.isdel=0) zs on zs.company_id=a.company_id 	
 join compy_basicinfo cb on cb.company_id=zs.company_id and cb.is_del=0   and zs.exposure not in ('证券','银行')	
 where a.rpt_timetype_cd=1 and a.combine_type_cd =1  and a.data_ajust_type=3 and to_char(a.rpt_dt,'yyyymmdd') =  '20161231' ;
 
 ------------------------------------证券
select zs.EXPOSURE ,zs.company_id,cb.company_nm, to_char(a.rpt_dt,'yyyymmdd') ,  			
net_profit	,
account_pay	,
account_rec	,
agent_trade_security	,agent_trade_security_last_y	,agent_trade_security_bf_last_y	,
agent_uw_security	,agent_uw_security_last_y	,agent_uw_security_bf_last_y	,
bond_pay	,
borrow_fund	,
buy_sellback_fasset	,
cagent_trade_security	,cagent_trade_security_last_y	,cagent_trade_secu_bf_last_y	,
client_fund	,
derive_fasset	,
derive_financedebt	,
dividend_rec	,
employee_pay	,
fvalue_fasset	,
fvalue_fliab	,
fvalue_income	,
gdeposit_pay	,
interest_pay	,
interest_rec	,
invest_income	,
lend_fund	,
lt_borrow	,
manage_exp	,
marginout_fund	,
monetary_fund	,
net_profit	,net_profit_last_y	,net_profit_bf_last_y	,
operate_exp	,
operate_profit	,operate_profit_last_y	,operate_profit_bf_last_y	,
operate_reve	,operate_reve_last_y	,operate_reve_bf_last_y	,
salary_pay	,
salary_pay_last_y	,
saleable_fasset	,
secu_sub_003	,secu_sub_003_last_y	,secu_sub_003_bf_last_y	,
secu_sub_011	,secu_sub_011_last_y	,secu_sub_011_bf_last_y	,
sell_buyback_fasset	,
settlement_provision	,
st_bond_rec	,
st_borrow	,
sum_asset	,sum_asset_last_y	,sum_asset_bf_last_y	,
sum_liab	,
sum_parent_equity	,
sum_profit	,sum_profit_last_y	,sum_profit_bf_last_y	,
sum_sh_equity	,
tax_pay	
 from compy_finance a 
 join compy_finance_last_y  b on a.company_id = b.company_id and a.rpt_dt = b.rpt_dt  and a.rpt_timetype_cd=b.rpt_timetype_cd  			
 join compy_finance_bf_last_y c on a.company_id = c.company_id and a.rpt_dt = c.rpt_dt  and a.rpt_timetype_cd=c.rpt_timetype_cd			
 join(select b.exposure,a.* from compy_exposure a join exposure b on a.exposure_sid = b.exposure_sid where a.client_id=5 and a.is_new=1 and a.isdel=0) zs on zs.company_id=a.company_id 	
 join compy_basicinfo cb on cb.company_id=zs.company_id and cb.is_del=0   and zs.exposure =  '证券公司' 	
 where a.rpt_timetype_cd=1 and a.combine_type_cd =1  and a.data_ajust_type=3 and to_char(a.rpt_dt,'yyyymmdd') =  '20161231' ;
 
--------------------------------------银行
select zs.EXPOSURE ,zs.company_id,cb.company_nm, to_char(a.rpt_dt,'yyyymmdd') ,  
accept_deposit	,accept_deposit_last_y	,accept_deposit_bf_last_y,
asset_devalue_loss	,
buy_sellback_fasset	,
buy_sellback_fasset_last_y	,
cash_and_depositcbank	,
cash_and_depositcbank_last_y	,
commn_reve	,commn_reve_last_y	,commn_reve_bf_last_y，
deposit_infi	,
deposit_infi_last_y	,
fvalue_fasset	,
fvalue_fasset_last_y	,
held_maturity_inv	,
held_maturity_inv_last_y	,
int_exp	,
int_reve	,
intn_reve	,intn_reve_last_y	,intn_reve_bf_last_y,
invest_rec	,invest_rec_last_y	,invest_rec_bf_last_y,
lend_fund	,
lend_fund_last_y	,
loan_advances	,loan_advances_last_y	,loan_advances_bf_last_y,
lte_quity_inv	,
lte_quity_inv_last_y	,
net_profit	,net_profit_last_y	,net_profit_bf_last_y,
operate_exp	,
operate_manage_exp	,
operate_profit	,
operate_reve	,operate_reve_last_y	,operate_reve_bf_last_y,
other_exp	,
other_reve	,
saleable_fasset	,
saleable_fasset_last_y	,
sum_asset	,sum_asset_last_y	,sum_asset_bf_last_y,
sum_liab	,
sum_sh_equity	,
sum_sh_equity_last_y,sum_sh_equity_bf_last_y	
 from compy_finance a 
 join compy_finance_last_y  b on a.company_id = b.company_id and a.rpt_dt = b.rpt_dt  and a.rpt_timetype_cd=b.rpt_timetype_cd  			
 join compy_finance_bf_last_y c on a.company_id = c.company_id and a.rpt_dt = c.rpt_dt  and a.rpt_timetype_cd=c.rpt_timetype_cd			
 join(select b.exposure,a.* from compy_exposure a join exposure b on a.exposure_sid = b.exposure_sid where a.client_id=5 and a.is_new=1 and a.isdel=0) zs on zs.company_id=a.company_id 	
 join compy_basicinfo cb on cb.company_id=zs.company_id and cb.is_del=0   and zs.exposure =  '银行' 	
 where a.rpt_timetype_cd=1 and a.combine_type_cd =1  and a.data_ajust_type=3 and to_char(a.rpt_dt,'yyyymmdd') =  '20161231' ;
 